### ISSUE TITLE
Exception because 'capabilities' is null

### ISSUE THREAD

**Issue by PyvesB** [briandealwis/gore#1]
Hello! 👋🏻 

I noticed your project on GitHub and wanted to try it out to work on a Go project in Eclipse. Unfortunately, when I open a Go file, exceptions similar to the following are recorded in the Error Log view:
```
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4j.ServerCapabilities.getColorProvider()" because "capabilities" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4j.ServerCapabilities.getColorProvider()" because "capabilities" is null
	at org.eclipse.lsp4e.operations.color.DocumentColorProvider.isColorProvider(DocumentColorProvider.java:105)
	at org.eclipse.lsp4e.LanguageServiceAccessor.lambda$15(LanguageServiceAccessor.java:590)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	... 6 more
```

Note that I'm using the latest versions of gopls (v0.7.4) and Eclipse (2021-12) at the time of writing. Is there anything else I need to configure somewhere? Or is this a problem with lsp4e?

**Comment by briandealwis** [comment]
Oops missed this! That looks to be a problem with lsp4e, though I haven’t seen it.  I usually live at HEAD and use the latest snapshots from

https://download.eclipse.org/tm4e/snapshots
https://download.eclipse.org/lsp4e/snapshots

**Comment by PyvesB** [comment]
No luck even with the latest snapshots of lsp4e and tm4e.

**Comment by briandealwis** [comment]
Odd, I don't encounter this issue — you may have other LSPs installed that are tickling this bug.  But it's an easy patch: https://github.com/eclipse/lsp4e/pull/40

BTW: you will likely hit https://github.com/golang/go/issues/49501.  I haven't tried tracking down why it happens in LSP4e, but there's an easy patch for gopls in https://github.com/golang/tools/pull/358.

**Comment by briandealwis** [comment]
I'll close this as the exception is not actually specific to Gore.

**Comment by PyvesB** [comment]
Thanks, will give it another try when the lsp4e patch is merged!

Yes, I'm familiar with the `file:` prefix inconsistencies, I investigated the exact same problem with the Ruby language server, see here: https://github.com/PyvesB/eclipse-solargraph/issues/17. :)
