### ISSUE TITLE
No views in session and error loading packages

### ISSUE THREAD

**Issue by PyvesB** [briandealwis/gore#2]
Hello again! 👋🏻 

I'm still trying to get Gore to work, but have been unsuccessful so far. Since #1, I updated to the latest lsp4e snapshot, 0.13.9.202201201104, and to the latest gopls release, 0.7.5.

When I open a Go file, the plugin is able to find the language server executable, as it logs `GORE: Found gopls at ...` with the right path. However, immediately after it logs the following error message:
```
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: no views in session
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$4(LanguageServerWrapper.java:260)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: no views in session
	... 11 more
```

A popup then gets continuously duplicated several times per second, quickly making the IDE unresponsive and slowing down the whole system:
<img width="450" alt="Screenshot 2022-01-22 at 20 50 01" src="https://user-images.githubusercontent.com/10694593/150653510-691a5636-0100-4a50-9ee4-5c44d7af5d7f.png">

The error message is truncated, but it claims that it can't load packages as it seemingly can't find the go command. This is odd given that it's able to find gopls, and that gopls starts happily when launched from the command line.

Any ideas?

**Comment by briandealwis** [comment]
Gore will try to find `gopls` in the PATH but if not found will otherwise look in ~/go/bin (and maybe some other places; I forget). I suspect that you’re encountering a difference in the PATH between your desktop session and your command line. 

I should check and warn if the `go` binary isn’t found. Perhaps I should append the resolver location to the PATH before launching `gopls`?.

**Comment by PyvesB** [comment]
Ah yes, the following line must always resolve to `~/go/bin` regardless of whether it's run from the command line or a desktop app:
https://github.com/briandealwis/gore/blob/e22e5f5eaec82652f2cb91e701926d99340a1cec/ca.mt.gore/src/ca/mt/gore/GoServer.java#L130

That's probably why it can find gopls, but not go itself.

You're probably correct in saying that it's a path issue. One way to solve the issue would be to execute commands with a login shell, so that the command line environment is picked up when running processes via Eclipse. A few language server clients do this, e.g.:
* https://github.com/PyvesB/eclipse-solargraph/blob/00d7295ee64f1bfd39da41196b1038f867be7250/eclipse-solargraph-plugin/src/main/java/io/github/pyvesb/eclipse_solargraph/utils/CommandHelper.java#L35
* https://github.com/eclipse/wildwebdeveloper/blob/7734ce2000c519c765b77f9a3668f638cdd0dc79/org.eclipse.wildwebdeveloper.embedder.node/src/org/eclipse/wildwebdeveloper/embedder/node/NodeJSManager.java#L145

**Comment by PyvesB** [comment]
Unfortunately, the problem persists with the latest changes.

**Comment by briandealwis** [comment]
I got a report that the CD job failed so the change may not be live. Will look this evening.

**Comment by briandealwis** [comment]
Ok, fixed! Give it a whirl.  I should really write some tests 🙄

**Comment by PyvesB** [comment]
The good news is that the error and popup spam have gone away. However, the plugin still doesn't seem to be working. This is the only thing that comes up in the error log, from lsp4e:
```
server 'ca.mt.gore.server.go' not available
```

**Comment by briandealwis** [comment]
ok should be fixed now :hangdog-expression:

**Comment by PyvesB** [comment]
Tested: unfortunately we're back to square one with the initial error I reported.

**Comment by briandealwis** [comment]
@PyvesB where is your `go` binary found?

From what I can see with other `gopls` bindings, this `no views in session` error indicates that the `go` binary can't be found on the `PATH`.  I have the Go SDK installed via Homebrew in `/opt/homebrew`.  If I launch Eclipse with a minimal `PATH=/usr/bin:/bin`, where `goals` is found in `~/go/bin`, then I get this `no views in session` error.

Anyways, I've added #9 to log the updated `PATH`.

**Comment by PyvesB** [comment]
Here's the output of `which` from the command line:
```
which go    
//usr/local/bin/go

which gopls
/Users/pierreyves.bigourdan/go/bin/gopls
```

> Anyways, I've added https://github.com/briandealwis/gore/pull/9 to log the updated PATH.

I'm seeing messages indicating that `GORE: Could not find the go binary`, but no `PATH` update messages.

**Comment by briandealwis** [comment]
The  environment seen by the IDE launched from the desktop may be different from that in your shell. I added more logging to GORE to output where the go binary is found and their versions.

**Comment by PyvesB** [comment]
> The environment seen by the IDE launched from the desktop may be different from that in your shell.

Yes, that's what I tried highlighting in https://github.com/briandealwis/gore/issues/2#issuecomment-1019449455. Launching the language server using a login shell, as do other language server clients, would probably solve this problem. I don't think it's reasonable to expect users to tinker about with their _eclipse.ini_ file to get Eclipse's path right. :)
